<?php

namespace CryptoPrice\Symbol;

/**
 * Class CoinMarketCap
 * @package CryptoPrice\Symbol
 */
class CoinMarketCap
{
    /**
     * @param $symbol
     * @return array
     */
    public static function get($symbol)
    {
        $symbols = [
            'bitcoin' => 'BTC',
            'ethereum' => 'ETH',
            'ripple' => 'XRP',
            'tether' => 'USDT',
            'bitcoin-cash' => 'BCH',
            'litecoin' => 'LTC',
            'binance' => 'BNB',
            'eos' => 'EOS',
            'bitcoin-sv' => 'BSV',
            'stellar' => 'XLM',
            'tron' => 'TRX',
            'unus' => 'LEO',
            'cardano' => 'ADA',
            'monero' => 'XMR',
            'chainlink' => 'LINK',
            'huobi' => 'HT',
            'iota' => 'MIOTA',
            'dash' => 'DASH',
            'tezos' => 'XTZ',
            'mexc' => 'MEXC',
            'cosmos' => 'ATOM',
            'ethereum' => 'ETC',
            'neo' => 'NEO',
            'maker' => 'MKR',
            'usd' => 'USDC',
            'crypto' => 'CRO',
            'nem' => 'XEM',
            'dogecoin' => 'DOGE',
            'ino' => 'INO',
            'ontology' => 'ONT',
            'basic' => 'BAT',
            'zcash' => 'ZEC',
            'paxos' => 'PAX',
            'insight' => 'INB',
            'hedgetrade' => 'HEDG',
            '0x' => 'ZRX',
            'trueusd' => 'TUSD',
            'vechain' => 'VET',
            'abbc' => 'ABBC',
            'holo' => 'HOT',
            'qtum' => 'QTUM',
            'prizm' => 'PZM',
            'luna' => 'LUNA',
            'thorenext' => 'THX',
            'decred' => 'DCR',
            'ravencoin' => 'RVN',
            'zb' => 'ZB',
            'thorecoin' => 'THR',
            'bitcoin-gold' => 'BTG',
            'swipe' => 'SXP',
            'centrality' => 'CENNZ',
            'educare' => 'EKT',
            'v-systems' => 'VSYS',
            'omisego' => 'OMG',
            'nano' => 'NANO',
            'synthetix' => 'SNX',
            'digibyte' => 'DGB',
            'kucoin' => 'KCS',
            'algorand' => 'ALGO',
            'lisk' => 'LSK',
            'augur' => 'REP',
            'bittorrent' => 'BTT',
            'siacoin' => 'SC',
            'dai' => 'DAI',
            'dimension' => 'EON',
            'bitcoin-diamond ' => 'BCD',
            'mixin' => 'XIN',
            'karatgold' => 'KBC',
            'waves' => 'WAVES',
            'icon' => 'ICX',
            'silverway' => 'SLV',
            'maximine' => 'MXM',
            'theta' => 'THETA',
            'bitshares' => 'BTS',
            'monacoin' => 'MONA',
            'gaps' => 'GAP',
            'quant' => 'QNT',
            'bitbook' => 'BXK',
            'komodo' => 'KMD',
            'bytecoin' => 'BCN',
            'hypercash' => 'HC',
            'maidsafecoin' => 'MAID',
            'bytom' => 'BTM',
            'flexacoin' => 'FXC',
            'bitforex' => 'BF',
            'verge' => 'XVG',
            'beldex' => 'BDX',
            'energi' => 'NRG',
            'crypto' => 'MCO',
            'nexo' => 'NEXO',
            'aeternity' => 'AE',
            'dynamic' => 'DTR',
            'iostoken' => 'IOST',
            'ftx' => 'FTT',
            'steem' => 'STEEM',
            'ardor' => 'ARDR',
            'aurora' => 'AOA',
            'okb' => 'OKB',
            'crpt' => 'CRPT',
            'minebee' => 'MB',
        ];

        return isset($symbols[$symbol]) ? $symbols[$symbol] : null;
    }
}